- _posts/2016-11-27-bachelorkolloq-schmidt.md
Next entry for BAKolloquium 2016/17
> Add ad for BAKolloquium w/ Kevin Schmidt

- _config.yml
- _github_config.yml
- _uberspace_config.yml
- mitmachen.md
> Mitgliederformular

- _posts/2016/2016-09-15-SoAkRueckblick.md
SoAk 2016 Rückblick Post erstellt
> Alexbirne patch 1

- _posts/2017/2017-01-20-bachelorkolloq-philhoffmann.md
- _posts/2017/2017-01-21-bachelorkolloq-chrgeister.md
- _posts/2017/2017-01-22-bachelorkolloq-constmeyer.md
Dates are slightly modified to preserve display order.
> Add remaining ads for BAK. 

- _posts/2017/2017-05-04-hackathon.md
Und hier nochmal der Hackathon-Post, bitte lesen
> post about Hackathon 2017

- _posts/2017/2017-02-08-soak2017-werbung.md
- _posts/2017/2017-05-04-soak-werbung-2.md
- ueber_uns/satzung_und_leitbild.md
Fixed some typographical errors.
> Kecksdose fix typo 1

- _data/categories.yml
- praktikumsboerse.md
> fix praktikumsboerse

- ueber_uns/vorstand.md
> WIP: Vorstand 2017

- _posts/2017/2017-06-28-otto.md
Stellenausschreibungen Praktikant/Werksstudent Otto
> Stellenausschreibung Otto

- stipendien/deutschland.md
- stipendien/goingabroad.md
- stipendien/initiativ.md
> Stipendien corrections

- jobboerse/_posts/2017-05-30-point8.md
- jobboerse/_posts/2017-06-09-asta1.md
- jobboerse/_posts/2017-06-09-asta2.md
- jobboerse/_posts/2017-06-09-mpi.md
- jobboerse/_posts/2017-06-13-nsg.md
- jobboerse/_posts/2017-06-14-zeb1.md
- jobboerse/_posts/2017-06-14-zeb2.md
- jobboerse/_posts/2017-06-28-otto.md
Machts denke ich etwas übersichtlicher und man muss die Kategorie nicht mehr angeben.
> Move jobboerse posts to own directory

- _posts/2017/2017-10-12-bachelorkolloq.md
Please review this post, especially line 17ff.: item "**02.11.2017** Hubertus Kaiser" with TeX content. I'm not able to check the site myself - issues w/ Homebrew.
> Add overview for BAKolloquium 2017/18

- _data/navigation.yml
- termine.html
Einfache Tabelle mit den Terminen, guckt mal rein, welche noch Fehlen, bis jetzt sind nur Absolventenfeier und SoAk drin.
> Add termin uebersicht

- _uberspace_config.yml
This *should* fix the footer formatting. (I thought I already opened this PR)
> Try to fix #169

- _posts/2018/2018-05-03-physikon.md
- termine.html
bitte mal durchlesen, ob das sinn macht.
> post physikon

- ueber_uns/gremien.html
> Update 1. Vorsitzende

- wall_of_fame/_posts/2018-07-23-afillmer.md
Habe vor allem das yaml gefixt. Das Bild wurde nämlich nicht angezeigt. Außerdem hab ich den Untertitel etwas gekürzt und ein paar Paragraphen hinzugefügt, um das besser zu lesen.
Könnte man bei den anderen posts evtl. auch noch machen...
> Fix the yaml, remove trailing spaces, fine tune paragraphs

- _includes/footer.html
- assets/css/bootstrap-custom.scss
> Fix 169 try 2

- images/impressum.svg
> Fix impressum.svg

- vereinsleben/bachelorkolloquium.md
Version "Bachelor-Kolloquium" shall be used consistently. Also, use the hyphenated term "Bachelor-" over word conjunctions.
> Rename "Bachelorkolloquium" to "Bachelor-Kolloquium"

- _posts/2019/2019-04-03-hackathon_smart_home_werbung.md
> Hackathon Smart Home Werbung

- _posts/2019/2019-04-02-soak-werbung.md
> fixed typo of soak date in teaser

- ueber_uns/impressum.md
This one will close #234. Ping @mennthor @hmoldenhauer
> Remove contact regarding "§ 55 Abs.2 RStV"

- ueber_uns/gremien.html
Mailsymbole zur Erreichbarkeit hinzugefügt.
Jetzt müssen nur noch die Mails richtig weiter geleitet werden.
> Mailsymbols

- ueber_uns/gremien.html
> Fix gremien

- _posts/2019/2019-06-02-hackathon_smart_home_bericht.md
Zusammenfassung zum Hackathon vom 24. bis 26. Mai 2019 im Tagungshaus Grend in Essen
> Smart home bericht

- termine.html
Change Westfalenpark to Romberpark in 'Termine'  (PeP im Park)
> change to Rombergpark

- _posts/2020/2020-08-04-toolbox-special.md
added post for the toolbox-workshop 2020
> Toolbox announcement for 2020

- mitmachen.html
- ueber_uns/gremien.html
Die Teams müssen eventuell noch abgestimmt/erweitert werden.
> Neuer Vorstand und Teams

- mitmachen.html
> Update roomnumber K2

- termine.html
- [ x] All included images are public domain images or their respective licenses are respected (e.g. attribution for CC-BY)
- [ x] Images are reduced to around 2000px at the long edge and in jpg format
> add physikon to calendar, make bold font for table headline

- _data/navigation.yml
- _posts/2018/2018-05-03-physikon.md
- _posts/2019/2019-03-22-physikon.md
- _posts/2019/2019-06-26-bericht-physikon.md
- _posts/2020/2020-03-16-physikon-absage.md
- _posts/2021/2021-03-26-physikon.md
- termine.html
- vereinsleben/physikon.md
- [ x] All included images are public domain images or their respective licenses are respected (e.g. attribution for CC-BY)
- [x ] Images are reduced to around 2000px at the long edge and in jpg format
> Add physikon to vereinsleben

- images/bankverbindung.svg
> Export text to path in bankverbindung.svg

- README.md
> added build-essential package for Ubuntu installation instructions

- jobboerse/_posts/2022-06-15-tng.md
> add tng post to jobboerse

- ueber_uns/gremien.html
my jekyll command still does not run, so pls check:
> removed Henning from the Vorstand site, as he wished

- jobboerse/_posts/2022-07-08-amprion.md
my jekyll command still doesn't work, so pls check:
> added amprion werkstudentenstelle data lab

- _posts/2022/2022-07-08-toolbox.md
- termine.html
> Toolbox Workshop 2022 → own post + termine

- jobboerse/_posts/2022-04-14-tkbilstein.md
> fix link to job description

- Gemfile
> Pin html-proofer to 4

- _data/navigation.yml
- stipendien/faq-purdue.md
- stipendien/goingabroad.md
> Update purdue pages

- vereinsleben/soak.md
> remove old soak date

- _posts/2022/2022-11-01-bakolloquium.md
Please have a look.
Anno and Martins surnames I don't know.
> Fix and add new dates for BK

- _posts/2022/2022-11-01-bakolloquium.md
- _posts/2022/2022-12-12-bewerbungs_workshop.md
> Added Workshop (and BA-Kolloq update)

- mitmachen.html
Add link to pep database for registration. Embed the link also in the logo.
Embed the link to contact via mail in the logo at the bottom.
> Add links to mitmachen page

- jobboerse/_posts/2023-01-09-vetvise.md
- [x ] All included images are public domain images or their respective licenses are respected (e.g. attribution for CC-BY)
- [x ] Images are reduced to around 2000px at the long edge and in jpg format
> add vetvise job offers to jobboerse

- _posts/2022/2022-11-01-bakolloquium.md
> Add zoom links to Bachelorkolloq

- ueber_uns/gremien.html
no mistakes concerning spelling or gendering
> corrected Finanzreferentin into Finanzreferent

- jobboerse/_posts/2023-04-19-raith.md
my jekyll command does not work again, so pls shortly check whether everything looks fine :)
> added entry for jobboerse raith

- jobboerse/_posts/2023-04-19-raith.md
Raith wollte noch eine weitere Stelle veröffentlicht haben, die habe ich noch hinzugefügt; sollte also alles klappen
> slight change in the latest jobboerse file

- jobboerse/_posts/2023-05-08-tng.md
> add tng techday to jobboerse

- jobboerse/_posts/2023-07-13-rdn.md
can not test build with jekyll but should be okay.
> added rdn post to jobboerse.

- _data/gremien.yml
> fix typo: "Jahannes" Lamers

- mitmachen.html
> Fix room and phone number

- _posts/2023/2023-08-24-toolbox.md
- vereinsleben/toolbox.md
- [x ] All included images are public domain images or their respective licenses are respected (e.g. attribution for CC-BY)
- [x ] Images are reduced to around 2000px at the long edge and in jpg format
> Toolbox Workshop 2023 Post

- _includes/carousel.html
- assets/css/bootstrap-custom.scss
> Fix wall of fame, fixes #537

- _posts/2023/2023-10-16-bakolloquium.md
> Fix post for bachelorkolloq

- mitmachen.html
> Change room number

- _posts/2023/2023-10-16-bakolloquium.md
> Add new speaker and fix name error

- _posts/2023/2023-10-16-bakolloquium.md
> Fix typo Lars to Lasse

- _posts/2023/2023-10-16-bakolloquium.md
> Add new dates and speakers

- _data/gremien.yml
- mitmachen.html
- ueber_uns/gremien.html
> Exchange Lars and Jan

- _data/gremien.yml
- ueber_uns/gremien.html
> Change Herdieckerhoff to Wagner

- jobboerse/_posts/2024-02-29-comnovo.md
> Add comnovo jobboerse entry

- termine.html
> add Absolventenfeier, PhysiKon and SoAk dates

- jobboerse/_posts/2024-06-03-tuev.md
> Jobboerse tuev

- _posts/2024/2024-08-14-toolbox.md
> Toolbox post für 2024

- _data/gremien.yml
- images/impressum.svg
- mitmachen.html
> change name from Schmidt to Schmitz

- _posts/2024/2024-11-15-bakolloquium.md
> Add first post for BK 24/25

- _posts/2024/2024-11-15-bakolloquium.md
> Add speaker for second slot of BK

- jobboerse/_posts/2024-12-03-amprion.md
> add amprion jobs

- _posts/2024/2024-12-12-bakolloquium.md
here a new post for the Bachelorkolloquium
> Add new post for BK

- _posts/2025/2025-01-16-bakolloquium.md
> Add new BK post

- _posts/2025/2025-01-16-bakolloquium.md
> Fix 2025 BK post

- _posts/2025/2025-01-16-bakolloquium.md
> Update BK post

- Gemfile.lock
- vereinsleben/soak.md
Ein paar Infos zur SoAk 2025 für Teilnehmer.
> info für SoAk2025

- jobboerse/_posts/2025-03-05-fi.md
adding job offers of finanz informatik
> add joboffers finanz informatik

- jobboerse/_posts/2025-03-05-fi.md
> Update Finanz Informatik Stellenangebot

- jobboerse/_posts/2025-05-05-deichmann.md
> add job offer deichmann
